project_id = "vmmosextmuuibhuyeqkq"

[functions.track-event]
verify_jwt = false

[functions.identify-lead]
verify_jwt = false

[functions.session-heartbeat]
verify_jwt = false

[functions.sync-activecampaign]
verify_jwt = false